apiVersion: v1
kind: Namespace
metadata:
  name: jobs
---
apiVersion: v1
kind: Secret
metadata:
  namespace: jobs
  name: aws-route53-creds
type: Opaque
data:
  aws_access_key_id: "<my_aws_access_key_id>"
  aws_secret_access_key: "<my_aws_secret_access_key>"
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  namespace: jobs
  name: aws-dns-updater
spec:
  schedule: "*/3 * * * *"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: aws-route53-creds
          containers:
          - name: aws-dns-updater
            image: docker.io/swhurl/aws-dns-updater:latest
            env:
              - name: AWS_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    name: aws-route53-creds
                    key: aws_access_key_id
              - name: AWS_SECRET_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: aws-route53-creds
                    key: aws_secret_access_key
              - name: DOMAIN
                value: "example.com."
              - name: TYPE
                value: "A"
              - name: RECORDS
                value: "example.com,*.example.com"
              - name: HOSTED_ZONE_ID
                value: "<hosted_zone_id>"
          restartPolicy: OnFailure
